"""Parallel Speculative Decoding - Token Reuse Cache.

This module implements the ReuseCache mechanism for Parallel-SD,
which stores pre-computed draft token branches and enables cache
hit reuse to skip draft model computation.
"""

import logging
import time
from dataclasses import dataclass, field

logger = logging.getLogger(__name__)


@dataclass
class ReuseCacheEntry:
    """Cache entry for a single branch.

    Stores the continuation tokens generated by a branch,
    used for cache HIT recovery.
    """
    continuation_tokens: list[int]
    base_position: int = 0


class ReuseCache:
    """Per-request Reuse Cache for Parallel Speculative Decoding.

    Stores pre-computed draft token branches keyed by token prefix tuples.
    Supports exact match lookup with optional half-cache-hit fallback
    (prefix match when top_k=1).

    The cache is populated each propose() round with branches generated
    from target model hidden_states, then queried with the actual
    sampled_token_ids to find a matching branch.

    Args:
        num_speculative_tokens: Number of draft tokens per branch.
        enable_half_cache_hit: Enable prefix matching fallback
            (only effective when top_k=1).
    """

    def __init__(
        self,
        num_speculative_tokens: int,
        enable_half_cache_hit: bool = False,
    ):
        self.num_speculative_tokens = num_speculative_tokens
        self.enable_half_cache_hit = enable_half_cache_hit
        self._cache: dict[tuple[int, ...], ReuseCacheEntry] = {}

        # Statistics
        self._hit_count: int = 0
        self._miss_count: int = 0
        self._half_hit_count: int = 0

        # Latency tracking
        self._total_lookup_time_ns: int = 0
        self._total_store_time_ns: int = 0
        self._lookup_count: int = 0
        self._store_count: int = 0

    def store_branch(
        self,
        lookup_key: tuple[int, ...],
        branch_tokens: list[int],
        base_position: int = 0,
    ) -> None:
        """Store a branch's continuation tokens in the cache.

        Args:
            lookup_key: Tuple of token IDs used as the cache key.
                For DECODE mode: input_ids[1:pos+1] + (root_token,)
                For PREFILL mode: (root_token,)
            branch_tokens: List of continuation token IDs generated
                by the draft model for this branch.
            base_position: Starting position index for this branch.
        """
        start = time.monotonic_ns()

        entry = ReuseCacheEntry(
            continuation_tokens=branch_tokens,
            base_position=base_position,
        )
        self._cache[lookup_key] = entry

        elapsed = time.monotonic_ns() - start
        self._total_store_time_ns += elapsed
        self._store_count += 1

        logger.debug(
            "ReuseCache store: key=%s, tokens=%s, base_pos=%d",
            lookup_key, branch_tokens, base_position,
        )

    def lookup(self, lookup_key: list[int]) -> list[int] | None:
        """Look up continuation tokens for the given key.

        First tries exact match. If exact match fails and
        half-cache-hit is enabled, tries prefix match
        (all tokens except the last one match).

        Args:
            lookup_key: List of token IDs to look up.
                Typically sampled_token_ids with -1 filtered out.

        Returns:
            List of continuation token IDs if cache hit, None if miss.
        """
        start = time.monotonic_ns()
        key_tuple = tuple(lookup_key)

        # Exact match
        entry = self._cache.get(key_tuple)
        if entry is not None:
            self._hit_count += 1
            elapsed = time.monotonic_ns() - start
            self._total_lookup_time_ns += elapsed
            self._lookup_count += 1
            logger.debug(
                "ReuseCache HIT: key=%s -> tokens=%s",
                key_tuple, entry.continuation_tokens,
            )
            return list(entry.continuation_tokens)

        # Half-cache-hit: prefix match (only when enabled)
        if self.enable_half_cache_hit and len(key_tuple) > 1:
            prefix = key_tuple[:-1]
            for cached_key, cached_entry in self._cache.items():
                if len(cached_key) == len(key_tuple) and \
                        cached_key[:-1] == prefix:
                    self._half_hit_count += 1
                    elapsed = time.monotonic_ns() - start
                    self._total_lookup_time_ns += elapsed
                    self._lookup_count += 1
                    logger.debug(
                        "ReuseCache HALF-HIT: key=%s, "
                        "matched_key=%s -> tokens=%s",
                        key_tuple, cached_key,
                        cached_entry.continuation_tokens,
                    )
                    return list(cached_entry.continuation_tokens)

        # Miss
        self._miss_count += 1
        elapsed = time.monotonic_ns() - start
        self._total_lookup_time_ns += elapsed
        self._lookup_count += 1
        logger.debug("ReuseCache MISS: key=%s", key_tuple)
        return None

    def clear(self) -> None:
        """Remove all entries from the cache."""
        self._cache.clear()
        logger.debug("ReuseCache cleared")

    @property
    def size(self) -> int:
        """Number of entries in the cache."""
        return len(self._cache)

    def get_statistics(self) -> dict[str, int]:
        """Return cache hit/miss/half_hit statistics.

        Returns:
            Dict with keys: hit, miss, half_hit.
        """
        return {
            "hit": self._hit_count,
            "miss": self._miss_count,
            "half_hit": self._half_hit_count,
        }

    def get_latency_statistics(self) -> dict[str, float]:
        """Return average latency statistics in microseconds.

        Returns:
            Dict with keys: avg_lookup_us, avg_store_us.
        """
        avg_lookup = (
            (self._total_lookup_time_ns / self._lookup_count / 1000)
            if self._lookup_count > 0 else 0.0
        )
        avg_store = (
            (self._total_store_time_ns / self._store_count / 1000)
            if self._store_count > 0 else 0.0
        )
        return {
            "avg_lookup_us": avg_lookup,
            "avg_store_us": avg_store,
        }

    def reset_statistics(self) -> None:
        """Reset all statistics counters to zero."""
        self._hit_count = 0
        self._miss_count = 0
        self._half_hit_count = 0
        self._total_lookup_time_ns = 0
        self._total_store_time_ns = 0
        self._lookup_count = 0
        self._store_count = 0
